#!/usr/bin/env bash

###################################
############# CONFIG ##############
###################################

hc() {
    herbstclient "$@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all

##################################
########## KEY BINDINGS ##########
##################################

Mod=Mod4  

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}" 

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# splitting frames 
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

# tags #
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Apps
hc keybind $Mod-f spawn alacritty -e ranger
hc keybind $Mod-p spawn rofi -show drun
hc keybind $Mod-r spawn /home/gabriel/Scripts/rofi-files
hc keybind $Mod+s spawn /home/gabriel/Scripts/rofi-search
hc keybind $Mod-w spawn /home/gabriel/Scripts/windowlocation
hc keybind $Mod-x spawn /home/gabriel/Scripts/power-menu.sh
hc keybind $Mod-t spawn alacritty -e htop

hc keybind Shift-b spawn /home/gabriel/Scripts/ram
hc keybind Shift-d spawn /home/gabriel/Scripts/time
hc keybind Shift-m spawn /home/gabriel/Scripts/volume+
hc keybind Shift-n spawn /home/gabriel/Scripts/volume-
hc keybind Shift-u spawn /home/gabriel/Scripts/Void-Updates

hc keybind $Mod-F1 spawn firefox
hc keybind $Mod-F2 spawn nautilus

# layouting
hc keybind $Mod-Shift-s remove
hc keybind $Mod-n floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-l pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse on

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent


###################################
############## THEMES #############
###################################


# THEME #
#-------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#888888'
hc set frame_border_normal_color '#111111'
hc set frame_bg_normal_color '#141414'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.normal.color '#6d6d6d'
hc attr theme.active.color '#ffffff'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#888888'
hc attr theme.actie.outer_color '#888888'
hc attr theme.background_color '#141414'


##################################
############## GAPS ##############
##################################

hc set window_gap 28
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0


##################################
############# RULES ##############
##################################

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock


# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
#    "$panel" "$monitor" &
#done


##################################
############# START ##############
##################################

picom &
nitrogen --restore &
xset r rate 300 50 &
xset -dpms &
xset s off &
numlockx on &
dunst &
polkit-xfce-authentication-agent-1 &
